# Generated by Django 5.1 on 2024-08-20 17:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_appointment_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default=datetime.datetime.now, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
    ]
