# Generated by Django 5.1 on 2024-08-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appointment_patient_remove_appointment_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
