# Generated by Django 5.1 on 2024-08-22 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appointment_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
        migrations.AddField(
            model_name='message',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
